# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo Build started
      - yarn run build
  post_build:
    commands:
      - echo Build completed
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - dist/index.html
    - dist/js/*
    - dist/images/*
    - dist/assets/*
